### ISSUE TITLE
[Feature-improvement] Writing focus shows StatusBar

### ISSUE THREAD

**Issue by u8slvn** [davisriedel/obsidian-typewriter-mode#78]
Hi Davis,
If you are writing to a goal, I think word count is an essential stat to show, even in focus mode. It could be great to let users choose whether they want to hide the status bar or not.

Adding the following CSS snippet do the trick perfectly, so it's just a suggestion.

```css
.ptm-focus-mode .status-bar {
  display: flex !important;
}
```
